### ISSUE TITLE
Login doesn't work anymore as of last week or so

### ISSUE THREAD

**Issue by camrentm** [BackTrak/StreamDeckLolLoginPlugin#1]
If you press the button for the plugin, it just opens the client and doesn't enter the ID or passwords. Not sure if this is just my end but it very recently stopped working after a couple months of usage. Love this plugin so hope it gets fixed soon!

**Comment by BackTrak** [comment]
This should be fixed now: https://github.com/BackTrak/StreamDeckLolLoginPlugin/releases/download/v1.2.0.2/com.zaphop.lollogin.sdPlugin.zip

I have submitted it to the StreamDeck store, and the new version should go up in a week or so. 

Thanks,
-BT

**Comment by camrentm** [comment]
Awesome! Thanks for updating so quickly. I’ll install this version manually to get back to using it. Cheers
